addpath('./matlab/')
%  vl_compilenn('enableGpu',true,...
%              'cudaRoot', '/usr/local/cuda-8.0/',...
%              'cudaMethod','nvcc')
 vl_compilenn('enableGpu',true,...
             'cudaRoot', 'C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0/',...
             'cudaMethod','nvcc')

% vl_compilenn()
